In [1]:
#Numpy Functions

In [2]:
import numpy as np

In [3]:
#arange()

In [4]:
#np.arange(start, end, steps)
ar_1d = np.arange(1,13)
print(ar_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [5]:
odd_arr = np.arange(1,13,2)
print(odd_arr)

[ 1  3  5  7  9 11]


In [6]:
#linspace()

In [7]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [8]:
#reshape()

In [9]:
ar_2d = ar_1d.reshape(3,4)
print(ar_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
ar_2d = ar_1d.reshape(2,3,2)
print(ar_2d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [11]:
ar=np.arange(1,13).reshape(2,6)
print(ar)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [12]:
#ravel()

In [13]:
ar_1d.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [14]:
#flatten()

In [15]:
ar_1d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [16]:
#transpose()

In [17]:
ar_1d.transpose()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [18]:
ar_1d.T

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])